# Development Profile Configuration
logging:
  level:
    root: INFO
    com.ulpf: DEBUG
    org.springframework.jdbc: DEBUG
jwt:
    secret: ${JWT_SECRET}
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
